[package]
name = "graphqxl_synthesizer"
version = "0.21.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphqxl_parser = { path = '../graphqxl_parser' }
indexmap = "1.9.1"

