[package]
name = "graphqxl_transpiler"
version = "0.28.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphqxl_parser = { path = '../graphqxl_parser' }
pest = "2.0"
regex = "1.7.0"
