name: Release

on:
  push:
    tags:
      - 'v**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: graphqxl
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  release-node-graphqxl:
    runs-on: ubuntu-latest
    needs:
      - upload-assets
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gabotechs/node-graphqxl
          token: ${{ secrets.PAT }}
      - run: |
          VERSION="${GITHUB_REF_NAME:1}"
          jq ".version=\"$VERSION\"" package.json > _package.json
          mv _package.json package.json
          git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
          git config --global user.name  $(git --no-pager show -s --format='%an' HEAD)
          git commit -a -m "bump: version $VERSION"
          git push origin main

