name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    if: github.event.head_commit.message != 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - id: Coverage
        uses: actions-rs/grcov@v0.1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}

      - name: Install bump tool
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces

      - name: Config git
        run: git config --global user.name "Github Actions"

      - name: Bump version
        uses: actions-rs/cargo@v1
        env:
          GIT_USER: Github Actions
          GIT_PASS: ${{ secrets.CI_TOKEN }}
        with:
          command: workspaces
          args: version minor -y --no-git-commit

      - name: push
        run: |
          git add .
          git commit -m "tag"
          git push 
          git push --tags
