name: Test/Tag

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-10-09 # Fixed so that it can be cached
          profile: minimal
          components: clippy
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all

  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-10-09 # Fixed so that it can be cached
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: Coverage
        id: Coverage
        uses: actions-rs/grcov@v0.1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}

  tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - test
      - clippy
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
      - name: Install bump tool
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces

      - name: Bump version
        uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: version minor -y --no-git-commit

      - name: Tag
        run: |
          version=`grep '^version = ' Cargo.toml | sed 's/version = //; s/\"//; s/\"//'`
          git config --global user.email "gabimtme@gmail.com"
          git config --global user.name "Automatic bumper"
          git add .
          git commit -m "tag: v$version" 
          git tag "v$version"
          git push
          git push --tags

